# Generated by Django 3.2.8 on 2021-10-06 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('due_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('startedAt', models.TimeField()),
                ('finishedAt', models.TimeField()),
                ('duration', models.TimeField()),
                ('date', models.DateField()),
                ('projectId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='projectsapi.project')),
            ],
        ),
    ]
